name: listtextfield
description: Provides you a textfield and accompanying controller that users can visually type separated lists into, such as a list of email recipients. 
version: 0.0.1
repository: https://github.com/Meghatronics/list-text-field

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
